Old Bundler makes error #11
It seems that the cause of following error is old Bundler.
> NoMethodError: undefined method `spec' for nil:NilClass

Add update Bundler processes.